dubbo:
  application:
    name: forex-user
  registry:
    address: zookeeper://localhost:2181?client=curator
  scan:
    base-packages: com.emeraldfrost.forexuser.service.impl
  protocol:
    port: 20883

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forex_user?serverTimezone=PRC&useSSL=false
    username: root
    password:

server:
  port: 0
