spring:
  dynamic:
    datasource:
      # ??master??????????
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3316/db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC
        username: root
        password:
      slave1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3326/db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC
        username: root
        password:
        # ???????????0????1
        weight: 3
      slave2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3336/db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC
        username: root
        password:
        # ???????????0????1
        weight: 2

logging:
  level:
    root: info
    com.emeraldfrost: debug